# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Type check
        run: yarn type-check
        
      - name: Lint
        run: yarn eslint .
        
      - name: Security scan
        run: yarn audit
        
      - name: Test
        run: yarn test
        
      - name: Build
        run: yarn build
        env:
          NEXT_PUBLIC_UNSPLASH_ACCESS_KEY: ${{ secrets.NEXT_PUBLIC_ACCESS_KEY }}
          NEXT_PUBLIC_UNSPLASH_API_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          
      - name: Performance check
        run: |
          yarn add -D lighthouse
          npx lighthouse http://localhost:3000 --output=json --output-path=./lighthouse-report.json